# follow-service runs on port 8085
server.port=8085
spring.application.name=follow-service

spring.datasource.url=jdbc:mysql://localhost:3306/connectsphere_follow?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=divyansh
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT must match all other services exactly
jwt.secret=connectsphere_super_secret_key_change_this_in_production_min_32_chars

# follow-service calls auth-service to resolve userId -> username for FOLLOW notifications
auth.service.url=http://localhost:8081

# post-service CALLS follow-service (not the other way around for feed)
# follow-service fires FOLLOW notifications to notification-service
notification.service.url=http://localhost:8086

logging.level.com.connectsphere=DEBUG
