# Server
server.port=8081

# Application name
spring.application.name=auth-service

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/connectsphere_auth?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=divyansh
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=connectsphere_super_secret_key_change_this_in_production_min_32_chars
jwt.expiration=86400000

# Google OAuth
# Set this to the Web client ID from Google Cloud Console.
google.oauth.client-id=296720816901-35flv9m985lu940g31tqaktuf799nlf0.apps.googleusercontent.com

# Logging
logging.level.com.connectsphere=DEBUG
logging.level.org.springframework.security=INFO

# search-service URL auth-service calls this to index users
search.service.url=http://localhost:8088

app.jms.deactivation-queue=account.deactivation
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bhatt11divyansh@gmail.com
spring.mail.password=qpvx jjhh lbcm xznn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
