# media-service runs on port 8087
server.port=8087
spring.application.name=media-service

# MySQL own schema
spring.datasource.url=jdbc:mysql://localhost:3306/connectsphere_media?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=divyansh
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT must match all other services exactly
jwt.secret=connectsphere_super_secret_key_change_this_in_production_min_32_chars

# Cloudinary same account used by post-service
cloudinary.cloud_name=dyi8qdv3p
cloudinary.api_key=917714253593674
cloudinary.api_secret=drL1tBbp1nvRgGGkCPNk0AmEDbM

# Story expiry scheduler runs every 5 minutes to purge expired stories
# fixedDelay = 300000ms = 5 minutes
story.expiry.check.interval.ms=300000

# Multipart file upload limits
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

logging.level.com.connectsphere=DEBUG
